services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ncc-bot-interview-english
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MEZON_TOKEN=${MEZON_TOKEN}
      - MEZON_BOT_ID=${MEZON_BOT_ID}
      - MEZON_AGENT_ID=${MEZON_AGENT_ID}
      - AGENT_BASE_URL=${AGENT_BASE_URL}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ncc-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: ncc-bot-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=bot_interview

volumes:
  redis-data:


networks:
  app-network:
    driver: bridge
